config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  resources :cocktails, only: [:show, :create, :index, :new, :destroy] do
    resources :doses, only: [:create, :destroy]
  end
  resources :doses, only: [:destroy]

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  validates :description, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :ingredient, :scope => [:cocktail]
  validates :cocktail, presence: true
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show, :update, :edit, :destroy ]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to action: 'index'
  end

  def destroy
    @cocktail.destroy
    redirect_to action: 'index'
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :show]

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to @cocktail
    else
      render 'cocktails/show'
    end
  end

  def edit
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    if @dose.destroy
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/views/cocktails/edit.html.erb
<h1>Cocktail#edit</h1>
<p>Find me in app/views/cocktail/edit.html.erb</p>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<div class="row">
<% @cocktails.each do |cocktail| %>
  <div class="col-xs-4">
    <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
    <ul>
      <% cocktail.doses.each do |dose| %>
        <li><%= dose.description %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/cocktails/new.html.erb
<h1>Add a new Cocktail</h1>
<p>Fill the form</p>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name, label: 'cocktail name' %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class='text-center'>
  <h1><%= @cocktail.name %></h1>

  <% @cocktail.doses.each do |dose| %>
    <p><%= dose.description %> (<%= dose.ingredient.name %>)</p>
    <p><%= dose.ingredient.name %></p>
  <% end %>


  <%= link_to 'Back', cocktails_path %>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.error_notification %>
    <%= f.input :description, placeholder: '3cl'%>
    <%= f.association :ingredient %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>
  <%= render 'shared/navbar' %>

<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_cocktail.png", class: 'avatar avatar-bordered' %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "New cocktail"), new_cocktail_url, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>